In [21]:
from numpy import random, dot,exp,array

X = array([[0,0,1],[1,1,1],[1,0,1],[0,1,1]])
y = array([[0,1,1,0]]).T

print(X)
print(y)

[[0 0 1]
 [1 1 1]
 [1 0 1]
 [0 1 1]]
[[0]
 [1]
 [1]
 [0]]


In [22]:
random.seed(1)
weights = random.random((3,1))*2-1
#print(f"weights:{weights}")

In [23]:
def fp(X,weights):
    z = dot(X,weights)
    output = 1/(1+exp(-z))
    #print(f"z:{z}")
    #print(f"output:{output}")
    return output

def bp(y,output):
    error = y-output
    slope = output*(1-output)
    delta = error*slope
    #print(f"error:{error}")
    #print(f"slope:{slope}")
    #print(f"delta:{delta}")
    return delta 

In [24]:
for it in range(10000):
    output = fp(X,weights)
    delta = bp(y,output)
    weights = weights+dot(X.T,delta)
#print(f"weights:{weights}")

In [25]:
predict = fp([[1,1,0]],weights)
print(f"predict:{predict}")

predict:[[0.9999225]]
