In [1]:
from numpy import random, dot,exp,array

X = array([[0,0,1],[0,1,1],[1,0,1],[1,1,1]])
y = array([[0,1,1,0]]).T

print(X)
print(y)

[[0 0 1]
 [0 1 1]
 [1 0 1]
 [1 1 1]]
[[0]
 [1]
 [1]
 [0]]


In [2]:
random.seed(1)
w0 = random.random((3,4))*2-1
w1 = random.random((4,1))*2-1

In [3]:
def fp(input):
    l1 = 1/(1+exp(-dot(input,w0)))
    l2 = 1/(1+exp(-dot(l1,w1)))
    #print(f"l1:{l1}")
    #print(f"l2:{l2}")
    return l1,l2

def bp(l1,l2,y):
    error = y-l2
    slope = l2*(1-l2)
    l1_delta = error*slope

    l0_slope = l1*(1-l1)
    l0_error = l1_delta.dot(w1.T)
    l0_delta = l0_error*l0_slope
    
    #print(f"l1_delta:{l1_delta}")
    #print(f"l0_delta:{l0_delta}")
    return l0_delta,l1_delta 

In [4]:
for it in range(10000):
    l0 = X
    l1,l2 = fp(l0)
    l0_delta,l1_delta = bp(l1,l2,y)     

    w1 = w1+dot(l1.T,l1_delta)
    w0 = w0+dot(l0.T,l0_delta)


In [5]:
predict = fp([[0,1,1]])[1]
print(f"predict:{predict}")

predict:[[0.99101005]]
